site_name: Thermotar Docs

theme: 
  name: material
  palette:
    - media: '(prefers-color-scheme: light)'
      scheme: default
      primary: red  
      accent: red
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: '(prefers-color-scheme: dark)' ## Obey the system color scheme 
      scheme: slate
      primary: red  
      accent: red
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    # can use navigation_depth to allow more layers of docs to be shown in the sidebar
nav:
  - Thermotar Docs: index.md
  - tutorials.md
  - How-To Guides: how-to-guides.md
  - Reference:
    - Chunk: 
      - Chunk1: 'reference/chunk.md'

    - Thermo: 'reference/thermo.md'
    - Intersects: 'reference/interface.md'
  - explanation.md

plugins:
  - mkdocstrings
  - search

